### PR TITLE
Ft 156577840 nag user to resolve issue 

### PR DESCRIPTION
**Pull request by tibetegya**
#### What does this PR do?
Nag a user to resolve an issue like when a check is down and sends them notifications after a specified period
#### Description of Task to be completed?
The system should keep nagging the user every so often until they resolve the job that has gone down
#### How should this be manually tested?
1. Install the project and install the requirements.txt
2.Run the commands below
3.You should have send email configured 

cd to hc-rogue-one
``` python manage.py sendalerts```
in another terminal
``` python manage.py sendalerts```

#### What are the relevant pivotal tracker stories?
#156577840

## Checklist: I completed these to help reviewers

- [x] My IDE is configured to follow the [**PEP8 Conventions**](https://www.python.org/dev/peps/pep-0008/)

  No? Unsure? -> configure your IDE, format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the develop branch.

  No? Unsure? -> execute command `git pull --rebase origin develop`

### CODE REVIEW

**Review by peterwade153 — COMMENTED** [review]
Good work, but please watch out the unnecessary spaces you line between lines code for to ease readability and maintainability of your code

**Comment by aenkya** [comment]
@tibetegya can you address the failing tests and merge conflicts?

**Comment by aenkya** [comment]
@tibetegya there are too many file changes. Restrict the PR to implemented changes

**Comment by aenkya** [comment]
Can you also squash your commits into one

**Comment by tibetegya** [comment]
@Elbertbiggs360 I actually changed all those files except for the migrations which are also needed

**Pull request closed without merging**
