### PR TITLE
FT 156577839 Add periodic reports

### PR DESCRIPTION
**Pull request by peterwade153**
#### What does this PR do?
Allow a user to set periodic intervals after which to receive reports about a check.
#### Description of Task to be completed?
User should be able to set periods either monthly or weekly or daily, after which they should receive reports about a check.
#### How should this be manually tested?
1. Install the project and install the requirements.txt
2.Run the commands below
3.You should have send email configured 
```
cd to hc-rogue-one
python manage.py shell
>>> from django.contrib.auth.models import User
>>> from hc.accounts.models import Member, Profile
>>> from hc.api.models import Check
>>> peter=User(username='peter',email='peterwade153@gmail.com')
>>> profile=Profile(user=peter,api_key='abc')
>>> check=Check(name='test',user=peter)
>>> peter.save()
>>> profile.save()
>>> check.save()
>>> peter.profile.send_report()
```
#### What are the relevant pivotal tracker stories?
#156577839

## Checklist: I completed these to help reviewers

- [x] My IDE is configured to follow the [**PEP8 Conventions**](https://www.python.org/dev/peps/pep-0008/)

  No? Unsure? -> configure your IDE, format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the develop branch.

  No? Unsure? -> execute command `git pull --rebase origin develop`

### CODE REVIEW

**Review by aenkya — CHANGES_REQUESTED** [review]
Too many file changes. Restrict the changes to the files you actually worked with

The checklist in your PR description indicates that this PR is not complete. Please update the checklist when you have done what it says

**Review by dondrzzy — COMMENTED** [review]
Ensure to always have about 50 to 150 edited lines  of code in your PR to ease the procedure of team code review. 448 lines of code edited limits the reviewers attentions to detail.
Endeavor to squash your commits

**Comment by peterwade153** [comment]
@Elbertbiggs360 i have worked on the multiple commits

**Comment by hariclerry** [comment]
Great job. The code looks neat . Though I suggest that you add doc strings to the code for easy readability and code maintentance.

**Comment by peterwade153** [comment]
i did add comments, to ease maintainablity

**Comment by hariclerry** [comment]
Okay. Yes I have seen it. Great then.

**Pull request merged**
