### PR TITLE
Ft landing page rework 156577854

### PR DESCRIPTION
**Pull request by hariclerry**
#### What does this PR do?
Create content on the landing page UI/UX to make users aware that they can create both Scheduled Tasks as well as Health Check Alerts using the system.
#### Description of Tasks to be complete
GIVEN users want to know what HealthChecks offers
when they access the landing page, then they should be aware of and get access to all features on the application.

#### How should this be manually tested?
1: Install the project and install the requirements.txt
2: Start the server by running; python manage.py runserver, open localhost  http://localhost:8080 in the browser
3: The landing page/home page is opened
4: You should be able to see the neccessary information displayed on the landing page.
#### What are the relevant pivotal tracker stories?
#156577854
#### Checklist: I completed these to help reviewers
- [x] My IDE is configured to follow the PEP8 Conventions

No? Unsure? -> configure your IDE, format the code and add the changes with git add . && git commit --amend
- [x] I have added tests to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

No? -> write tests and add them to this commit git add . && git commit --amend

- [x] All new and existing tests passed.

No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is based on the latest changes of the develop branch.

No? Unsure? -> execute command git pull --rebase origin develop

### CODE REVIEW

**Comment by hariclerry** [comment]
This feature does not require writing test so no test has been written for it. Please review the PR and let me know what you guys think.

**Review by aenkya — CHANGES_REQUESTED** [review]
@hariclerry good job!

Is there any particular reason as to why the CTA button saying `Get Started for Free` is not working?

The screenshot of the scheduled tasks also seems very out of line with the design of HealthChecks and won't be an accurate representation of what is going on in the application.

Can you also edit your PR description. The checklist has issues

**Comment by hariclerry** [comment]
@Elbertbiggs360, I have fixed the issues of CTA button and screenshots. Can you please shade more light on the PR description and checklists? I have edited it though.

**Comment by aenkya** [comment]
Duplicate

**Pull request closed without merging**
